import { yieldgenreportQueryKey } from '@joinmarket-webui/joinmarket-api-ts/@tanstack/react-query'
import { yieldgenreport } from '@joinmarket-webui/joinmarket-api-ts/jm'
import type { ErrorMessage } from '@joinmarket-webui/joinmarket-api-ts/jm'
import { useQuery } from '@tanstack/react-query'
import { yieldgenReportToEarnReportEntries } from '@/components/earn/report/hooks/earnReportParser'
import { useApiClient } from '@/hooks/useApiClient'

// Re-export for consumers
export type { EarnReportEntry } from '@/components/earn/report/hooks/earnReportParser'

export function useQueryYieldgenReport({ enabled = true }: { enabled?: boolean } = {}) {
  const client = useApiClient()

  return useQuery<ReturnType<typeof yieldgenReportToEarnReportEntries>, ErrorMessage>({
    queryKey: yieldgenreportQueryKey(),
    queryFn: async ({ signal }) => {
      try {
        const response = await yieldgenreport({ client, signal })

        let lines: string[]
        // Wrong type generated by API! Try to parse actual format `{ yigen_data: [] }`!
        // see: https://github.com/JoinMarket-Org/joinmarket-clientserver/pull/1836 (last checked: 2026-03-09)
        const data = response.data as unknown
        if (data && typeof data === 'object' && 'yigen_data' in data && Array.isArray(data.yigen_data)) {
          lines = (data.yigen_data ?? []) as string[]
        } else {
          lines = response.data ?? []
        }

        // API returns string[] (CSV lines with header)
        return yieldgenReportToEarnReportEntries(lines)
      } catch (error: unknown) {
        // 404 is returned until the maker is started at least once
        if (error && typeof error === 'object' && 'status' in error && (error as { status: number }).status === 404) {
          return []
        }
        throw error
      }
    },
    enabled,
  })
}
