name: Build Storybook

on:
  push:
    branches:
      - devel
  workflow_dispatch:

jobs:
  deploy:
    runs-on: ubuntu-latest
    environment:
      name: github-pages
      url: ${{ steps.deployment.outputs.page_url }}

    steps:
      - name: Checkout
        uses: actions/checkout@v6

      - name: Setup Node.js
        uses: actions/setup-node@v6
        with:
          node-version-file: .nvmrc

      - name: Install
        run: npm clean-install --no-audit --no-fund

      - name: Build Storybook
        run: npm run storybook:Build
